name: sync submodule gitlab

on: [push]

jobs:
  build:
    name: sync submodule gitlab
    runs-on: self-hosted
    steps:
    - name: sync submodule gitlab 
      env:
        DEPLOY_KEY: ${{ secrets.NEXTFLOW_CI_KEY }}
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        eval "$(ssh-agent -s)"
        ssh-add - <<< "${DEPLOY_KEY}"
        rm -rf nextflow_ci
        git clone git@gitlab.internal.sanger.ac.uk:hgi-projects/nextflow_ci.git
        cd nextflow_ci
        git fetch --all
        export BRANCH=$(echo $GITHUB_REF | sed s/^refs\\/heads\\///g)
        echo full ref is $GITHUB_REF and branch is $BRANCH
        git checkout $BRANCH || \
          (echo branch does not exist && git checkout -b $BRANCH template && git push origin $BRANCH:$BRANCH)
        git branch --set-upstream-to=origin/$BRANCH $BRANCH
        git pull
        git submodule sync
        git submodule update --init --recursive --remote
        sed -i s"/branch = template$/branch = $BRANCH/"g .gitmodules
        git add .gitmodules && git commit --allow-empty -m "fixed .gitmodules" && git push -u origin
        git submodule sync
        git submodule update --init --recursive --remote
        git add nextflow_ci && git add .gitmodules && git commit --allow-empty -m "add submodule; ${{ github.event.head_commit.message }}; branch $BRANCH" && git push -u origin
